### PR TITLE
added card

### PR DESCRIPTION
**Pull request by abhijeetekad**
hacktoberfest participant

### CODE REVIEW

**Comment by MazontheMoon** [comment]
Added first contributor card for Hacktoberfest 2021 tribute project

**Comment by abhijeetekad** [comment]
Thank you

**Comment by abhijeetekad** [comment]
hii .. on hacktoberfest dashboard it is saying that this project is excluded.. is it?

**Comment by MazontheMoon** [comment]
Hi,
Can you give me the link for where you saw this?

**Comment by abhijeetekad** [comment]
Screenshot (427)
here is the screenshot

**Comment by MazontheMoon** [comment]
Hi,

Thanks for letting me know about this and I'm still looking into it and
will get back to you once I can check it out more

**Comment by abhijeetekad** [comment]
ok .. no worries

**Pull request merged**
